// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPAI6NpLh7Q31rGwS6V895bgfdz06KM-I',
    appId: '1:337236140756:web:7efef3e6b3af1301bc5141',
    messagingSenderId: '337236140756',
    projectId: 'responsive-page-cdf3d',
    authDomain: 'responsive-page-cdf3d.firebaseapp.com',
    storageBucket: 'responsive-page-cdf3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VtTtAGb2v2wlEd1oovVfw5zVF7eHl-w',
    appId: '1:337236140756:android:d7417deb4ec3d7b0bc5141',
    messagingSenderId: '337236140756',
    projectId: 'responsive-page-cdf3d',
    storageBucket: 'responsive-page-cdf3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDFlThmYnpTfvk1KU3njhRByoMoi5LSU',
    appId: '1:337236140756:ios:79b534de64c36e80bc5141',
    messagingSenderId: '337236140756',
    projectId: 'responsive-page-cdf3d',
    storageBucket: 'responsive-page-cdf3d.appspot.com',
    iosBundleId: 'com.vedasjad.responsivepage.responsivePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiDFlThmYnpTfvk1KU3njhRByoMoi5LSU',
    appId: '1:337236140756:ios:ea7da6d8d23a279fbc5141',
    messagingSenderId: '337236140756',
    projectId: 'responsive-page-cdf3d',
    storageBucket: 'responsive-page-cdf3d.appspot.com',
    iosBundleId: 'com.vedasjad.responsivepage.responsivePage.RunnerTests',
  );
}
